#!/bin/bash

# Проверяем, что файл JAR существует
if [ ! -f "./opt/app/app-0.0.1-SNAPSHOT.jar" ]; then
    echo "Файл JAR не найден!"
    exit 1
fi

# Запускаем приложение
java -jar "./opt/app/app-0.0.1-SNAPSHOT.jar"
echo "Spring boot app started"
